## 1D Array

In [6]:
import numpy as np
my_1d_arr = np.array([5, 7, 9, 3, 6])
print(my_1d_arr)
print(my_1d_arr.ndim)
print(my_1d_arr.shape)
print(my_1d_arr.size)

[5 7 9 3 6]
1
(5,)
5


## Multidimentional Array

In [13]:
multi_d_arr = np.array([[10, 1, 2, 3], [4, 5, 6, 7]])
                          
print(multi_d_arr)
print(multi_d_arr.ndim)
print(multi_d_arr.shape)
print(multi_d_arr.size)

[[10  1  2  3]
 [ 4  5  6  7]]
2
(2, 4)
8


## Arithmetic operations

In [14]:
multi_d_arr_modified = multi_d_arr*5
print(multi_d_arr_modified)
print(multi_d_arr+multi_d_arr_modified)
print(multi_d_arr-multi_d_arr_modified)
print(multi_d_arr*multi_d_arr_modified)
print(multi_d_arr/multi_d_arr_modified)

[[50  5 10 15]
 [20 25 30 35]]
[[60  6 12 18]
 [24 30 36 42]]
[[-40  -4  -8 -12]
 [-16 -20 -24 -28]]
[[500   5  20  45]
 [ 80 125 180 245]]
[[0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]]
