# Broadcasting

It refers to the ability of numpy to deal operations with operand arrays of different dimensions

In [4]:
import numpy as np 
arr_1 = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]) 
arr_2 = np.array([1, 1, 1, 1, 1])  

print(arr_1.ndim) # 2d array
print(arr_2.ndim) # 1d array

2
1


### Performing operation to show broadcasting

In [5]:
print(arr_1 + arr_2)

[[12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]
 [27 28 29 30 31]]


In [6]:
print(arr_1 - arr_2)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [7]:
print(arr_1 * arr_2)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
